# Generated by Django 2.0.5 on 2018-05-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxSite', '0002_auto_20180506_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='taxpayer_idCard_num',
            field=models.CharField(default='', max_length=32),
        ),
    ]
