# Generated by Django 2.0.5 on 2018-05-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxSite', '0003_auto_20180506_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='tax_tag',
            field=models.CharField(default='工资薪金所得', max_length=32),
        ),
    ]
